contact_links:
  - name: CCBR Discussions
    url: https://github.com/CCBR/CCBR_NextflowTemplate/discussions # TODO replace CCBR_NextflowTemplate in this link with TOOL_NAME
    about: Please ask and answer questions here.
